---
abstract: 'an ORM'
author:
  - 'Ruslan Zakirov <ruslan.zakirov@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.18'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Plum
name: Plum
no_index:
  directory:
    - inc
requires:
  Carp: 0
  Encode: 0
  JSON: 0
  perl: 5.16.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
